name: update precision

on:
  push:
    branches:
      - develop

jobs:
  determine-whether-update:
    name: Determine whether to update
    if: github.repository == 'PaddlePaddle/PaddleFormers'
    runs-on: ubuntu-latest
    outputs:
      need_change: ${{ steps.determine.outputs.need_change }}
    steps:
      - name: Determine whether to update
        id: determine
        run: |
          response=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/PaddlePaddle/PaddleFleet/commits/${{ github.sha }}/pulls)
          pr_number=$(echo $response | jq -r '.[0].url' | awk -F'/' '{print $NF}')
          set +e
          wget --no-proxy --no-check-certificate https://paddle-github-action.cdn.bcebos.com/PaddleFleet/precision/PaddleFormers_${pr_number}/precision_list.txt
          if [ $? -eq 0 ]; then
            echo "need_change=true" >> "$GITHUB_OUTPUT"
          else
            echo "need_change=false" >> "$GITHUB_OUTPUT"
          fi

  update-precision:
    name: Update precision
    needs: determine-whether-update
    if: determine-whether-update.outputs.need_change == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Clone PaddleFormers
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 100

      - name: Update precision (PaddleFormers)
        env:
          AK: ${{ secrets.AK }}
          SK: ${{ secrets.SK }}
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_ID: ${{ github.sha }}
          GITHUB_REPO_NAME: ${{ github.repository }}
        run: |
          bash -x tests/integration_test/update_precision.sh
          
        